- name: Checkov GitHub Action
  # You may pin to the exact commit or the version.
  # uses: bridgecrewio/checkov-action@00cc657f4d415593e5c8897bc87f490497ccb5f9
  uses: bridgecrewio/checkov-action@v12.641.0
  with:
    # directory with infrastructure code to scan
    directory: # optional, default is .
    # Run scan only on a specific check identifier (comma separated)
    check: # optional
    # Run scan on all checks but a specific check identifier (comma separated)
    skip_check: # optional
    # display only failed checks
    quiet: # optional
    # do not return an error code if there are failed checks
    soft_fail: # optional
    # run only on a specific infrastructure
    framework: # optional
    # comma separated list of external (custom) checks directories
    external_checks_dirs: # optional
    # comma separated list of external (custom) checks repositories
    external_checks_repos: # optional
    # The format of the output. cli, json, junitxml, github_failed_only
    output_format: # optional
    # download external terraform modules from public git repositories and terraform registry:true, false
    download_external_modules: # optional
    # log level
    log_level: # optional, default is WARNING
