name: build
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkov GitHub Action
        # You may pin to the exact commit or the version.
        # uses: bridgecrewio/checkov-action@00cc657f4d415593e5c8897bc87f490497ccb5f9
        uses: bridgecrewio/checkov-action@v12.641.0
